const ipcModules = [
  "./ipc/utils/activation.ipc.js",
  "./ipc/core/assignment/index.ipc.js",
  "./ipc/core/auditLog/index.ipc.js",
  "./ipc/core/bukid/index.ipc.js",
  "./ipc/reports/dashboard/index.ipc.js",
  "./ipc/core/paymentHistory/index.ipc.js",
  "./ipc/core/debtHistory/index.ipc.js",
  "./ipc/core/debt/index.ipc.js",
  "./ipc/core/payment/index.ipc.js",
  "./ipc/core/pitak/index.ipc.js",
  "./ipc/core/worker/index.ipc.js",
  "./ipc/utils/system_config/index.ipc.js",
  "./ipc/utils/windows_control.ipc.js",
  "./ipc/core/session/index.ipc.js",
  "./ipc/core/notification/index.ipc.js",
  "./ipc/utils/updater/index.ipc.js",
  "./ipc/utils/handlers/fileHandler.js",
  "./ipc/exports/audit/index.ipc.js",
  "./ipc/utils/worker_payment/index.ipc.js",
   "./ipc/core/themes/index.ipc.js",
   "./ipc/core/reminder/index.ipc.js",
];

module.exports = ipcModules;
